# This is a basic workflow to help you get started with Actions

name: BUILD_APK_BY_MANUAL

on:
  workflow_dispatch:
    inputs:
      x_branch:
        description: '指定sing-box分支'
        required: true
        default: 'main'
        type: choice
        options:
        - 'main'
      x_commit_id:
        description: '指定sing-box使用commit id版本'
        required: true
        default: 'HEAD~0'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '20'
    - name: java version
      run: |
        java --version

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: Install gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
